export const K = {
    
    // PHYSICS CONSTANTS
	SPRING_CONSTANT : 0.1,
	EQUILIBRIUM_DISPLACEMENT : 40,
	TIME_STEP : 0.8,
	FRICTION : 0.95,

	// DIMENSIONS OF PHASE SPACE
	W_0 : 2000,
	H_0 : 2000/1.618,

	PHASE_SPACE_LIMIT_RIGHT_MARGIN : 50,
	PHASE_SPACE_LIMIT_MINOR_MARGIN : 15,

	// VERT GAP BETWEEN NODE & LABEL
	NODE_LABEL_VERT_SPACING : 5,
	NODE_LABEL_HORIZ_SPACING : 5,
	NODE_LABEL_FONTFAMILY : '10pt Arial',

	// PERIOD OF GTK WINDOW TIMER TICK EVENT [that our handler is hooked into]
	TIMER_TICK_PERIOD : 500, // milliseconds

	MINIMUM_NODE_SELECTION_RADIUS : 50.0,

	//DEMO_GRAPH_SIZE : 11,
	DEMO_GRAPH_BRANCHING_CONST : 2,
	GENERATION_INTERVAL : 10.0 ,// seconds

	q_A: 15.0,
	q_B: 15.0,
	k: 200.0
};